baseURL = 'https://alxhill.dev/'
languageCode = 'en-us'
title = './alxhill.dev'
theme = 'archie'
copyright = "© Alexander Hill"
googleAnalytics = "G-Z2CCEVMECY"
paginate = 3

enableGitInfo = true

[params]
mode = "toggle"
useCDN = true
subtitle = "Small site for things I'm working on/thinking about. Mostly for my own records."
description = "alxhill dev page"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Devlogs"
url = "/devlogs"
weight = 3

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/alxhill"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/alxhill"