baseURL = 'https://alxhill.dev/'
languageCode = 'en-us'
title = 'alxhill.dev'
theme = 'archie'
copyright = "© Alexander Hill"
googleAnalytics = "G-Z2CCEVMECY"
paginate = 3

[[params]]
    mode = "toggle"
    subtitle = "Development log and blog posts"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Devlogs"
url = "/devlogs"
weight = 3

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/alxhill"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/alxhill"